export enum SocketEventType {
  TYPING_MESSAGE_EVENT = 'IS_TYPING',
  NEW_CHAT_MESSAGE_EVENT = 'NEW_MESSAGE',
  SEND_MESSAGE_EVENT = 'SEND_MESSAGE',
  JOIN_ROOM_EVENT = 'JOIN_ROOM',
  LEAVE_ROOM_EVENT = 'LEAVE_ROOM',
  SEEN_MESSAGE = 'SEEN_MESSAGE',
  SEND_SEEN_MESSAGE = 'SEND_SEEN_MESSAGE',
  ADD_USER = 'ADD_USER',
  ONLINE_USERS = 'ONLINE_USERS',
  CREATE_ROOM = 'CREATE_ROOM',
  NEW_ROOM = 'NEW_ROOM',
}
