apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "penpalmap-api-v2.fullname" . }}
  labels:
    {{- include "penpalmap-api-v2.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "penpalmap-api-v2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "penpalmap-api-v2.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "penpalmap-api-v2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "penpalmap-api-v2.jwt.secretName" . }}
                  key: {{ include "penpalmap-api-v2.jwt.accessTokenKey" . }}
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "penpalmap-api-v2.jwt.secretName" . }}
                  key: {{ include "penpalmap-api-v2.jwt.refreshTokenKey" . }}
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "penpalmap-api-v2.google.secretName" . }}
                  key: {{ include "penpalmap-api-v2.google.clientIdKey" . }}
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "penpalmap-api-v2.google.secretName" . }}
                  key: {{ include "penpalmap-api-v2.google.clientSecretKey" . }}
            - name: MJ_APIKEY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: {{ include "penpalmap-api-v2.mailjet.secretName" . }}
                  key: {{ include "penpalmap-api-v2.mailjet.apiKeyKey" . }}
            - name: MJ_APIKEY_PRIVATE
              valueFrom:
                secretKeyRef:
                  name: {{ include "penpalmap-api-v2.mailjet.secretName" . }}
                  key: {{ include "penpalmap-api-v2.mailjet.apiSecretKey" . }}
            - name: FRONTEND_URL
              value: {{ .Values.config.frontendURL }}
            - name: DB_NAME
              value: {{ .Values.config.postgresql.name }}
            - name: DB_HOST
              value: {{ .Values.config.postgresql.host }}
            - name: DB_PORT
              value: {{ .Values.config.postgresql.port | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "penpalmap-api-v2.postgresql.secretName" . }}
                  key: {{ include "penpalmap-api-v2.postgresql.usernameKey" . }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "penpalmap-api-v2.postgresql.secretName" . }}
                  key: {{ include "penpalmap-api-v2.postgresql.passwordKey" . }}
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "penpalmap-api-v2.minio.secretName" . }}
                  key: {{ include "penpalmap-api-v2.minio.usernameKey" . }}
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "penpalmap-api-v2.minio.secretName" . }}
                  key: {{ include "penpalmap-api-v2.minio.passwordKey" . }}
            - name: MINIO_SCHEME
              value: {{ .Values.config.minio.scheme }}
            - name: MINIO_HOST
              value: {{ .Values.config.minio.host }}
            - name: MINIO_PORT
              value: {{ .Values.config.minio.port | quote }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
