---
{{- if (include "penpalmap-api-v2.jwt.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpalmap-api-v2.jwt.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "penpalmap-api-v2.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.jwt.secretKeys.accessToken | quote }}: {{ ternary (randAlphaNum 12) .Values.config.jwt.accessTokenSecret (empty .Values.config.jwt.accessTokenSecret) }}
  {{ .Values.config.jwt.secretKeys.refreshToken | quote }}: {{ ternary (randAlphaNum 12) .Values.config.jwt.refreshTokenSecret (empty .Values.config.jwt.refreshTokenSecret) }}
{{- end }}
---
{{- if (include "penpalmap-api-v2.google.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpalmap-api-v2.google.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "penpalmap-api-v2.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.google.secretKeys.clientId | quote }}: {{ ternary (randAlphaNum 12) .Values.config.google.clientId (empty .Values.config.google.clientId) }}
  {{ .Values.config.google.secretKeys.clientSecret | quote }}: {{ ternary (randAlphaNum 12) .Values.config.google.clientSecret (empty .Values.config.google.clientSecret) }}
{{- end }}
---
{{- if (include "penpalmap-api-v2.mailjet.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpalmap-api-v2.mailjet.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "penpalmap-api-v2.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.mailjet.secretKeys.apiKey | quote }}: {{ ternary (randAlphaNum 12) .Values.config.mailjet.apiKey (empty .Values.config.mailjet.apiKey) }}
  {{ .Values.config.mailjet.secretKeys.apiSecret | quote }}: {{ ternary (randAlphaNum 12) .Values.config.mailjet.apiSecret (empty .Values.config.mailjet.apiSecret) }}
{{- end }}
---
{{- if (include "penpalmap-api-v2.postgresql.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpalmap-api-v2.postgresql.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "penpalmap-api-v2.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.postgresql.secretKeys.username | quote }}: {{ ternary (randAlphaNum 12) .Values.config.postgresql.username (empty .Values.config.postgresql.username) }}
  {{ .Values.config.postgresql.secretKeys.password | quote }}: {{ ternary (randAlphaNum 12) .Values.config.postgresql.password (empty .Values.config.postgresql.password) }}
{{- end }}
---
{{- if (include "penpalmap-api-v2.minio.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpalmap-api-v2.minio.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "penpalmap-api-v2.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.minio.secretKeys.username | quote }}: {{ ternary (randAlphaNum 12) .Values.config.minio.username (empty .Values.config.minio.username) }}
  {{ .Values.config.minio.secretKeys.password | quote }}: {{ ternary (randAlphaNum 12) .Values.config.minio.password (empty .Values.config.minio.password) }}
{{- end }}