---
{{- if (include "penpalmap-api-v2.jwt.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpalmap-api-v2.jwt.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "penpalmap-api-v2.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "penpalmap-api-v2.jwt.accessTokenKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.jwt.accessTokenSecret (empty .Values.config.jwt.accessTokenSecret) }}
  {{ include "penpalmap-api-v2.jwt.refreshTokenKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.jwt.refreshTokenSecret (empty .Values.config.jwt.refreshTokenSecret) }}
{{- end }}
---
{{- if (include "penpalmap-api-v2.google.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpalmap-api-v2.google.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "penpalmap-api-v2.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "penpalmap-api-v2.google.clientIdKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.google.clientId (empty .Values.config.google.clientId) }}
  {{ include "penpalmap-api-v2.google.clientSecretKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.google.clientSecret (empty .Values.config.google.clientSecret) }}
{{- end }}
---
{{- if (include "penpalmap-api-v2.mailjet.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpalmap-api-v2.mailjet.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "penpalmap-api-v2.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "penpalmap-api-v2.mailjet.apiKeyKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.mailjet.apiKey (empty .Values.config.mailjet.apiKey) }}
  {{ include "penpalmap-api-v2.mailjet.apiSecretKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.mailjet.apiSecret (empty .Values.config.mailjet.apiSecret) }}
{{- end }}
---
{{- if (include "penpalmap-api-v2.postgresql.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpalmap-api-v2.postgresql.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "penpalmap-api-v2.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "penpalmap-api-v2.postgresql.usernameKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.postgresql.username (empty .Values.config.postgresql.username) }}
  {{ include "penpalmap-api-v2.postgresql.passwordKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.postgresql.password (empty .Values.config.postgresql.password) }}
{{- end }}
---
{{- if (include "penpalmap-api-v2.minio.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpalmap-api-v2.minio.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "penpalmap-api-v2.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "penpalmap-api-v2.minio.usernameKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.minio.username (empty .Values.config.minio.username) }}
  {{ include "penpalmap-api-v2.minio.passwordKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.minio.password (empty .Values.config.minio.password) }}
{{- end }}