name: Version production
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
jobs:
  version:
    name: Create tag and push to GitHub
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new_tag }}
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: calc-new-version
        name: Calculate new version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: update-package-version
        name: Update package.json version
        run: |
          # Update package.json version with yq
          sudo snap install yq
          yq -i '.version = "${{ steps.calc-new-version.outputs.new_tag }}"' package.json
      - id: update-chart-version
        name: Update Chart.yaml version
        run: |
          # Update Chart.yaml version with yq
          sudo snap install yq
          yq -i '.version = ${{ steps.calc-new-version.outputs.new_tag }}' charts/penpalmap-api-v2/Chart.yaml
          yq -i '.appVersion = "${{ steps.calc-new-version.outputs.new_tag }}"' charts/penpalmap-api-v2/Chart.yaml
      - id: commit
        name: Commit and push changes
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: bump version to ${{ steps.calc-new-version.outputs.new_tag }}"
      - id: bump-version
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build and push docker image to Github Container Registry
    runs-on: ubuntu-latest
    needs: version
    permissions:
      contents: read
      packages: write
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: docker-login
        name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: repository-to-lowercase
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}
      - id: docker-build-push
        name: Build Docker image and push to Github Container Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.repository-to-lowercase.outputs.lowercase }}:${{ needs.version.outputs.new-version }}
            ${{ env.REGISTRY }}/${{ steps.repository-to-lowercase.outputs.lowercase }}:latest
